@startuml

skinparam classAttributeIconSize 0

class TemperaturVerlauf {
    - temperaturen : List<Temperatur>
    + add(Temperatur temperatur) : void
    + clear() : void
    + getCount() : int
}

@enduml